name: Auto Update Habit Tracker

on:
  push:
    branches: [ main ]
  workflow_dispatch: # 手動実行も可能

jobs:
  update-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install -g @github/cli
      
    - name: Update files
      run: |
        # ここでファイルの自動更新処理を記述
        echo "Files updated automatically"
        
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto update: $(date)"
          git push
        fi







